### ISSUE TITLE
Error: no gitconfig to be found at /private/tmp

### ISSUE THREAD

**Issue by gr2m** [RichardLitt/name-your-contributors#2]
When I ran

```
$ name-your-contributors hoodiehq --since=2016-02-01T00:20:000Z
```

I get 

```
Error: no gitconfig to be found at /private/tmp
    at /Users/gregor/.nvm/versions/node/v4.2.2/lib/node_modules/name-your-contributors/node_modules/gitconfiglocal/index.js:12:27
    at /Users/gregor/.nvm/versions/node/v4.2.2/lib/node_modules/name-your-contributors/node_modules/gitconfiglocal/index.js:45:48
    at FSReqWrap.cb [as oncomplete] (fs.js:212:19)
```

any idea?

```
$ node -v && npm -v
v4.2.2
3.7.3
```

**Comment by RichardLitt** [comment]
Huh. That is a new one. Looking into it.

**Comment by RichardLitt** [comment]
This should be fixed now. I wasn't escaping possible errors goodly enough. Your command worked for me!

```
🐕node cli.js hoodiehq --since=2016-02-01T00:20:000Z
[@Charlotteis](//github.com/Charlotteis) (Charlotte Spencer)
[@danreeves](//github.com/danreeves) (Dan Reeves)
[@espy](//github.com/espy) (Alex Feyerke)
[@girvo](//github.com/girvo) (Josh Girvin)
[@gr2m](//github.com/gr2m) (Gregor Martynus)
[@greenkeeperio-bot](//github.com/greenkeeperio-bot) (Greenkeeper)
[@HipsterBrown](//github.com/HipsterBrown) (Nick Hehr)
[@janl](//github.com/janl) (Jan Lehnardt)
[@jsimplicio](//github.com/jsimplicio) (Julia Simplicio)
[@kazekagegaara](//github.com/kazekagegaara) (Manit Singh Kalsi)
[@lewiscowper](//github.com/lewiscowper) (Lewis Cowper)
[@mikehedman](//github.com/mikehedman) (Mike Hedman)
[@nickcolley](//github.com/nickcolley) (Nick Colley)
[@nye](//github.com/nye) (Albert Sunyer)
[@patriciagarcia](//github.com/patriciagarcia) (Patricia Garcia)
[@ransomw](//github.com/ransomw) (Ransom Williams)
[@renrutnnej](//github.com/renrutnnej) (Jenn Turner)
[@savelbr](//github.com/savelbr) (Brecht Savelkoul)
[@toh82](//github.com/toh82) (Tobias Hartmann)
```

**Comment by gr2m** [comment]
aight :+1: now I get a "API rate limit exceeded" error, I will make a follow up issue
